# Generated by Django 4.2.4 on 2023-08-30 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название ингредиента')),
                ('unit_of_measure', models.CharField(max_length=64, verbose_name='Единица меры')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientToRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество ингр. в рецепте')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ingredient', verbose_name='Связь с ингредиентом')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Название тега')),
                ('hex_color', models.CharField(default='#ffffff', max_length=7, unique=True, verbose_name='Код цвета')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Слаг тега ')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='Название блюда')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка блюда')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(blank=True, verbose_name='Время приготовления в минутах')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('ingredients', models.ManyToManyField(through='api.IngredientToRecipe', to='api.ingredient', verbose_name='Ингредиенты рецепта')),
                ('tags', models.ManyToManyField(to='api.tag', verbose_name='Теги рецепта')),
            ],
        ),
        migrations.AddField(
            model_name='ingredienttorecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.recipe', verbose_name='Связь с рецептом'),
        ),
    ]
