# Generated by Django 4.2.4 on 2023-10-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ingredient_measurement_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
