# Generated by Django 4.2.4 on 2023-09-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriber',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='author',
            new_name='following',
        ),
    ]
