# Generated by Django 4.2.4 on 2023-09-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_title_recipe_name_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipes_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во рецептов'),
        ),
    ]
