version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  foodgram_db:
    container_name: foodgram_db
    image: postgres:13.10
    env_file:
      - ../.env 
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    container_name: foodgram_backend
    image: bar2les/foodgram_backend
    env_file: 
      - ../.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - foodgram_db

  frontend:
    container_name: foodgram_frontend
    image: bar2les/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
