# Generated by Django 4.2.4 on 2023-09-17 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_foodgramuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='podpis', to=settings.AUTH_USER_MODEL),
        ),
    ]
