# Generated by Django 4.2.4 on 2023-09-18 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_foodgramuser_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='podpis', to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
    ]
