# Generated by Django 4.2.4 on 2023-09-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_foodgramuser_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='follow',
        ),
    ]
