# Generated by Django 4.2.4 on 2023-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_foodgramuser_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='recipes_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во рецептов'),
        ),
    ]
