# Generated by Django 4.2.4 on 2023-10-04 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_foodgramuser_recipes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='is_subscribed',
        ),
    ]
